from tkinter import *






print("THE PROGRAM MAY FREEZE WHILE THE BOT IS BEING CREATED!")
root = Tk()
f = open("ApiDiscord.txt" ,"w")
root.geometry("800x800")
root.title("Bot generator")
e = Entry(root, width=200)
e.pack()
e.insert(0, "Put your api here! ")



def Clear():
    e.delete(0, END)


def Generate():
    api = e.get()
    with open("ApiDiscord.txt", "r+") as f:
        if api in f.read():
            print("It's already saved!")
        else:
            f.writelines(api + "\n")
    spacje = sum(n.isspace() for n in e.get()) #Checks the amount of spaces

    if len(api) == 59 and api.startswith('O') and spacje == 0:   
        Bot = open("Bot.py","w")
        with open("Bot.py", "r+") as Bot:
            Bot.write("#Automatically generated by Bot Generator" + "\n")
            Bot.write("import discord" + "\n" + "from discord import client" + "\n" + "from discord.ext import commands" + "\n")
            Bot.write("client = commands.Bot(command_prefix='-')" + "\n" + "#You can change the prefix to whatever thing you want" + "\n")
            Bot.write(f"@client.event \nasync def on_ready(): \n \t print('Bot starts working!') \n#You can delete that (It won't break your bot). It shows if bot is active or not \n")
            Bot.write(f"client.run('{api}')")
    else:
       e.delete(0,END)
       e.insert(0, "Please try again!") 





GenerateButton = Button(root, text = "Generate!", command = Generate).pack()
ClearButton = Button(root, text = "Clear", command=Clear).pack()



mainloop()
